name: GitHub CI
on:
  push:
    branches: [master]
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true
  
jobs:
  build-go-binary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin] # 需要打包的系统
        goarch: [amd64, arm64, arm, mips, mips64, mips64le, mipsle, 386] # 需要打包的架构
        exclude: # 排除某些平台和架构
          - goarch: arm64
            goos: windows
          - goarch: 386
            goos: darwin
          # arm 排除
          - goarch: arm
            goos: windows
          - goarch: arm
            goos: darwin

          # windows、darwin、android 排除 mips, mips64, mips64le, mipsle
          - goarch: mips
            goos: windows
          - goarch: mips64
            goos: windows
          - goarch: mips64le
            goos: windows
          - goarch: mipsle
            goos: windows

          - goarch: mips
            goos: darwin
          - goarch: mips64
            goos: darwin
          - goarch: mips64le
            goos: darwin
          - goarch: mipsle
            goos: darwin

          - goarch: mips
            goos: android
          - goarch: mips64
            goos: android
          - goarch: mips64le
            goos: android
          - goarch: mipsle
            goos: android

    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # 一个默认的变量，用来实现往 Release 中添加文件
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: 1.21 # 可以指定编译使用的 Golang 版本
          binary_name: "iptest" # 可以指定二进制文件的名称
          ldflags: -s -w -X "main.version=${{ github.ref_name }}"
          md5sum: false
      - name: Delete current release assets
        uses: andreaswilli/delete-release-assets-action@v2.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: Alpha
          deleteOnlyFromDrafts: false

      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: bin/

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: bin

      - name: Tag Repo
        uses: richardsimko/update-tag@v1.0.6
        with:
          tag_name: Alpha
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        if: ${{  success() }}
        with:
          tag: Alpha
          tag_name: Alpha
          files: bin/*
          generate_release_notes: true
